apiVersion: 1
datasources:
- name: Cortex
  type: prometheus
  access: proxy
  orgId: 1
  url: http://cortex-gateway/prometheus
  version: 1
  editable: true
  isDefault: true
  jsonData: 
    httpHeaderName1: "Authorization"
  secureJsonData: 
    httpHeaderValue1: "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiJkZW1vIiwidmVyc2lvbiI6MX0.J59fhMZjbAkm1nCfGB2kR2r3BEJScHoRWBgQUWve-BMFPX6N5SGERZkbKDRk7zExMcq6Tuvqn_E-MI6-a-gy-w"