global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: cortex
    static_configs:
      - targets: ['cortex']
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

remote_write:
  - url: http://cortex-gateway/api/v1/push
    authorization:
      credentials: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiJkZW1vIiwidmVyc2lvbiI6MX0.J59fhMZjbAkm1nCfGB2kR2r3BEJScHoRWBgQUWve-BMFPX6N5SGERZkbKDRk7zExMcq6Tuvqn_E-MI6-a-gy-w
    send_exemplars: true